### ISSUE TITLE
Stellaswap token icon has ugly white bg

### ISSUE THREAD

**Issue by Burtonium** [TalismanSociety/chaindata#131]
![image](https://github.com/TalismanSociety/chaindata/assets/9215927/0e885c76-45d1-4c83-bf63-1f151624ec56)

**Comment by alecdwm** [comment]
That logo doesn't come from this repo, it comes from [coingecko](https://www.coingecko.com/en/coins/stellaswap)

In the wallet we render logos as a square ([to support logos like this one](https://github.com/TalismanSociety/chaindata/blob/main/assets/tokens/vsdot.svg)) when they're from this repo, and we render all the coingecko ones [as a circle](https://github.com/TalismanSociety/talisman/blob/88e86c6ff67743d9db2e87a2b0cfda43d182db2d/apps/extension/src/ui/domains/Asset/AssetLogo.tsx#L68-L69)
