### ISSUE TITLE
Migrate squid deployment to manifest-based deployment

### ISSUE THREAD

**Issue by jonathanpdunne** [TalismanSociety/chaindata#42]
Details here:
https://docs.subsquid.io/deploy-squid/migration/

For the chaindata instance running in production, we should check this `dedicated` flag:
https://docs.subsquid.io/deploy-squid/scale/#dedicated

**Comment by alecdwm** [comment]
<div align="center">

![it is done](https://media0.giphy.com/media/3oKIPf3C7HqqYBVcCk/giphy.gif?cid=ecf05e47sxcf7l5j5vrwv5gk77wsalbi1thpom3oddxf026o&ep=v1_gifs_search&rid=giphy.gif&ct=g)

</div>
